### ISSUE TITLE
Add support for Bedrock Llama 2 13b model (meta.llama2-13b-chat-v1)

### ISSUE THREAD

**Issue by mirodrr** [langchain-ai/langchain#13316]
### System Info

I get following error just by adding model parameters to existing code that works with other models 

"Malformed input request: 2 schema violations found, please reformat your input and try again."

```
model_name = "meta.llama2-13b-chat-v1"
model_kwargs = {
"max_gen_len": 512,
"temperature": 0.2,
 "top_p": 0.9
}
bedrock_boto = boto3.client("bedrock-runtime", "us-east-1")
bedrock_llm = Bedrock(model_id=model_name, client=bedrock_boto,model_kwargs=model_kwargs)
bedrock_llm("Hello!")
```

### Who can help?

@hwchase17
@agola11

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [X] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. Attempt to call the new llama2 bedrock model like so:

```
model_name = "meta.llama2-13b-chat-v1"
model_kwargs = {
"max_gen_len": 512,
"temperature": 0.2,
 "top_p": 0.9
}
bedrock_boto = boto3.client("bedrock-runtime", "us-east-1")
bedrock_llm = Bedrock(model_id=model_name, client=bedrock_boto,model_kwargs=model_kwargs)
bedrock_llm("Hello!")
```

### Expected behavior

The Bedrock class would work successfully as it does for other BedRock models

**Comment by CarloNicolini** [comment]
Same error here with langchain 0.0.336.

The DOSU bot is confusing and wrong. Solution is simpler, there is a reason why you get the 2-schema validation errors. 
If you look at the body of the `Bedrock._prepare_input_and_invoke` the cases of 'cohere', 'anthropic', and other providers are **manually set**. 
There is the need to manually include the 'meta' provider by adding all the parts of the code containing match cases with the provider 'meta'.
In practice in the `body` one should modify the `inputText` key renaming it into `prompt`.
