### ISSUE TITLE
inconsistent performance of langchain rag

### ISSUE THREAD

**Issue by mhyeonsoo** [langchain-ai/langchain#16056]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.

### Example Code

```python
template = """
**Role:**
You are a helpful assistant.

**Context:**
You have to only use a reference stored document to generate a response.
CONTEXT: {context}

**Task:**
1. task 1
     - some important requirements for task 1
2. task 2
     - some important requirements for task 2  
3. task 3 
     - some important requirements for task 3
            
Question: {question}
Helpful Answer:

**Resource:** [reference source name]
"""
    
qa_prompt = ChatPromptTemplate.from_messages(
[
    ("system", template),
    MessagesPlaceholder(variable_name="chat_history"),
    ("user", "{question}"),
]
)
    
rag_chain = (
    RunnablePassthrough.assign(
        context=contextualized_question | retriever | format_docs
    )
    | qa_prompt
    | llm
)

response = rag_chain.invoke({"question": message, "chat_history": memory.get_history()})
    
print(response)
```

### Description

I tried to make the rag chain with the prompt.
In here, I found that the tasks mentioned in the prompt are sometimes followed, but sometimes not.
I would like to make the chain consistent for the user queries.
Is there way to do this?

### System Info

langchain==0.0.352

### Related Components

- [X] LLMs/Chat Models
- [X] Embedding Models
- [X] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

**Comment by mhyeonsoo** [comment]
Thanks @dosu-bot,

what is [INST] <<SYS>> these things in the prompt you mentioned?
